
export default [
    {
      small: 'CapsLock',
      shift: null,
      code: 'CapsLock',
      keycode: '0',
    },
    {
      small: 'ё',
      shift: 'Ё',
      code: 'Backquote',
      keycode: '192',
    },
    {
      small: '1',
      shift: '!',
      code: 'Digit1',
      keycode: '49',
    },
    {
      small: '2',
      shift: '"',
      code: 'Digit2',
      keycode: '50',
    },
    {
      small: '3',
      shift: '№',
      code: 'Digit3',
      keycode: '51',
    },
    {
      small: '4',
      shift: ';',
      code: 'Digit4',
      keycode: '52',
    },
    {
      small: '5',
      shift: '%',
      code: 'Digit5',
      keycode: '53',
    },
    {
      small: '6',
      shift: ':',
      code: 'Digit6',
      keycode: '54',
    },
    {
      small: '7',
      shift: '?',
      code: 'Digit7',
      keycode: '55',
    },
    {
      small: '8',
      shift: '*',
      code: 'Digit8',
      keycode: '56',
    },
    {
      small: '9',
      shift: '(',
      code: 'Digit9',
      keycode: '57',
    },
    {
      small: '0',
      shift: ')',
      code: 'Digit0',
      keycode: '48',
    },
    {
      small: '-',
      shift: '_',
      code: 'Minus',
      keycode: '189',
    },
    {
      small: '=',
      shift: '+',
      code: 'Equal',
      keycode: '187',
    },
    {
      small: 'Backspace',
      shift: null,
      code: 'Backspace',
      keycode: '8',
    },
    {
      small: 'Delete',
      shift: null,
      code: 'Delete',
      keycode: '46',
    },
    {
      small: 'Tab',
      shift: null,
      code: 'Tab',
      keycode: '9',
    },
    {
      small: 'й',
      shift: 'Й',
      code: 'KeyQ',
      keycode: '81',
    },
    {
      small: 'ц',
      shift: 'Ц',
      code: 'KeyW',
      keycode: '87',
    },
    {
      small: 'у',
      shift: 'У',
      code: 'KeyE',
      keycode: '69',
    },
    {
      small: 'к',
      shift: 'К',
      code: 'KeyR',
      keycode: '82',
    },
    {
      small: 'е',
      shift: 'Е',
      code: 'KeyT',
      keycode: '84',
    },
    {
      small: 'н',
      shift: 'Н',
      code: 'KeyY',
      keycode: '89',
    },
    {
      small: 'г',
      shift: 'Г',
      code: 'KeyU',
      keycode: '85',
    },
    {
      small: 'ш',
      shift: 'Ш',
      code: 'KeyI',
      keycode: '73',
    },
    {
      small: 'щ',
      shift: 'Щ',
      code: 'KeyO',
      keycode: '79',
    },
    {
      small: 'з',
      shift: 'З',
      code: 'KeyP',
      keycode: '80',
    },
    {
      small: 'х',
      shift: 'Х',
      code: 'BracketLeft',
      keycode: '219',
    },
    {
      small: 'ъ',
      shift: 'Ъ',
      code: 'BracketRight',
      keycode: '221',
    },
    {
      small: 'Enter',
      shift: null,
      code: 'Enter',
      keycode: '13',
    },
    {
      small: 'ф',
      shift: 'Ф',
      code: 'KeyA',
      keycode: '65',
    },
    {
      small: 'ы',
      shift: 'Ы',
      code: 'KeyS',
      keycode: '83',
    },
    {
      small: 'в',
      shift: 'В',
      code: 'KeyD',
      keycode: '68',
    },
    {
      small: 'а',
      shift: 'А',
      code: 'KeyF',
      keycode: '70',
    },
    {
      small: 'п',
      shift: 'П',
      code: 'KeyG',
      keycode: '71',
    },
    {
      small: 'р',
      shift: 'Р',
      code: 'KeyH',
      keycode: '72',
    },
    {
      small: 'о',
      shift: 'О',
      code: 'KeyJ',
      keycode: '74',
    },
    {
      small: 'л',
      shift: 'Л',
      code: 'KeyK',
      keycode: '75',
    },
    {
      small: 'д',
      shift: 'Д',
      code: 'KeyL',
      keycode: '76',
    },
    {
      small: 'ж',
      shift: 'Ж',
      code: 'Semicolon',
      keycode: '186',
    },
    {
      small: 'э',
      shift: 'Э',
      code: 'Quote',
      keycode: '222',
    },
    {
      small: '\\',
      shift: '/',
      code: 'Backslash',
      keycode: '220',
    },
    {
      small: 'Shift',
      shift: null,
      code: 'ShiftLeft',
      keycode: '16',
    },
    {
      small: '/',
      shift: '|',
      code: 'IntlBackslash',
      keycode: '191',
    },
    {
      small: 'я',
      shift: 'Я',
      code: 'KeyZ',
      keycode: '90',
    },
    {
      small: 'ч',
      shift: 'Ч',
      code: 'KeyX',
      keycode: '88',
    },
    {
      small: 'с',
      shift: 'С',
      code: 'KeyC',
      keycode: '67',
    },
    {
      small: 'м',
      shift: 'М',
      code: 'KeyV',
      keycode: '86',
    },
    {
      small: 'и',
      shift: 'И',
      code: 'KeyB',
      keycode: '66',
    },
    {
      small: 'т',
      shift: 'Т',
      code: 'KeyN',
      keycode: '78',
    },
    {
      small: 'ь',
      shift: 'Ь',
      code: 'KeyM',
      keycode: '77',
    },
    {
      small: 'б',
      shift: 'Б',
      code: 'Comma',
      keycode: '188',
    },
    {
      small: 'ю',
      shift: 'Ю',
      code: 'Period',
      keycode: '190',
    },
    {
      small: '.',
      shift: ',',
      code: 'Slash',
      keycode: '191',
    },
    {
      small: 'Shift',
      shift: null,
      code: 'ShiftRight',
      keycode: '16',
    },
    {
      small: 'Ctrl',
      shift: null,
      code: 'ControlLeft',
      keycode: '17',
    },
    {
      small: 'Alt',
      shift: null,
      code: 'AltLeft',
      keycode: '18',
    },
    {
      small: ' ',
      shift: null,
      code: 'Space',
      keycode: '32',
    },
    {
      small: 'Alt',
      shift: null,
      code: 'AltRight',
      keycode: '225',
    },
    {
      small: 'Ctrl',
      shift: null,
      code: 'ControlRight',
      keycode: '17',
    },
    {
      small: '&larr;',
      shift: null,
      code: 'ArrowLeft',
      keycode: '37',
    },
    {
      small: '&uarr;',
      shift: null,
      code: 'ArrowUp',
      keycode: '38',
    },
    {
      small: '&darr;',
      shift: null,
      code: 'ArrowDown',
      keycode: '40',
    },
    {
      small: '&rarr;',
      shift: null,
      code: 'ArrowRight',
      keycode: '39',
    },
    {
      small: '🕪',
      shift: null,
      code: 'Sound',
      keycode: '1000',
    },
  ];
  