import bird from '../assets/sounds/bird.mp3';
import angry from '../assets/sounds/angry.mp3';
import blouse from '../assets/sounds/blouse.mp3';
import boot from '../assets/sounds/boot.mp3';
import cat from '../assets/sounds/cat.mp3';
import chick from '../assets/sounds/chick.mp3';
import chicken from '../assets/sounds/chicken.mp3';
import coat from '../assets/sounds/coat.mp3';
import correct from '../assets/sounds/correct.mp3';
import cry from '../assets/sounds/cry.mp3';
import dance from '../assets/sounds/dance.mp3';
import dive from '../assets/sounds/dive.mp3';
import dog from '../assets/sounds/dog.mp3';
import dolphin from '../assets/sounds/dolphin.mp3';
import draw from '../assets/sounds/draw.mp3';
import dress from '../assets/sounds/dress.mp3';
import error from '../assets/sounds/error.mp3';
import failure from '../assets/sounds/failure.mp3';
import fish from '../assets/sounds/fish.mp3';
import fly from '../assets/sounds/fly.mp3';
import frog from '../assets/sounds/frog.mp3';
import giraffe from '../assets/sounds/giraffe.mp3';
import happy from '../assets/sounds/happy.mp3';
import horse from '../assets/sounds/horse.mp3';
import hug from '../assets/sounds/hug.mp3';
import jump from '../assets/sounds/jump.mp3';
import laugh from '../assets/sounds/laugh.mp3';
import lion from '../assets/sounds/lion.mp3';
import mouse from '../assets/sounds/mouse.mp3';
import open from '../assets/sounds/open.mp3';
import pants from '../assets/sounds/pants.mp3';
import pig from '../assets/sounds/pig.mp3';
import play from '../assets/sounds/play.mp3';
import point from '../assets/sounds/point.mp3';
import rabbit from '../assets/sounds/rabbit.mp3';
import ride from '../assets/sounds/ride.mp3';
import run from '../assets/sounds/run.mp3';
import sad from '../assets/sounds/sad.mp3';
import scared from '../assets/sounds/scared.mp3';
import sheep from '../assets/sounds/sheep.mp3';
import shirt from '../assets/sounds/shirt.mp3';
import shoe from '../assets/sounds/shoe.mp3';
import sing from '../assets/sounds/sing.mp3';
import skip from '../assets/sounds/skip.mp3';
import skirt from '../assets/sounds/skirt.mp3';
import smile from '../assets/sounds/smile.mp3';
import success from '../assets/sounds/success.mp3';
import surprised from '../assets/sounds/surprised.mp3';
import swim from '../assets/sounds/swim.mp3';
import tired from '../assets/sounds/tired.mp3';
import turtle from '../assets/sounds/turtle.mp3';

export default function getSound() {
    return {
        bird : new Audio(bird),
        angry : new Audio(angry),
        blouse : new Audio(blouse),
        boot : new Audio(boot),
        cat : new Audio(cat),
        chick : new Audio(chick),
        chicken : new Audio(chicken),
        coat : new Audio(coat),
        correct : new Audio(correct),
        cry : new Audio(cry),
        dance : new Audio(dance),
        dive : new Audio(dive),
        dog : new Audio(dog),
        dolphin : new Audio(dolphin),
        draw : new Audio(draw),
        dress : new Audio(dress),
        error : new Audio(error),
        failure : new Audio(failure),
        fish : new Audio(fish),
        fly : new Audio(fly),
        frog : new Audio(frog),
        giraffe : new Audio(giraffe),
        happy : new Audio(happy),
        horse : new Audio(horse),
        hug : new Audio(hug),
        jump : new Audio(jump),
        laugh : new Audio(laugh),
        lion : new Audio(lion),
        mouse : new Audio(mouse),
        open : new Audio(open),
        pants : new Audio(pants),
        pig : new Audio(pig),
        play : new Audio(play),
        point : new Audio(point),
        rabbit : new Audio(rabbit),
        ride : new Audio(ride),
        run : new Audio(run),
        sad : new Audio(sad),
        scared : new Audio(scared),
        sheep : new Audio(sheep),
        shirt : new Audio(shirt),
        shoe : new Audio(shoe),
        sing : new Audio(sing),
        skip : new Audio(skip),
        skirt : new Audio(skirt),
        smile : new Audio(smile),
        success : new Audio(success),
        surprised : new Audio(surprised),
        swim : new Audio(swim),
        tired : new Audio(tired),
        turtle : new Audio(turtle),
    }
}


